#page title
page_title                                : ARPlantsCare                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6477347902                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/applicationLogo-1024x1024.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ARPlantsCare                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Complementing reality with your plants!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alexey Taran                                
your_link                                 :                     
your_city                                 : Earth                                
email_address                             : essa.teryuavainen@gmail.com
telegram_username                         : alextar04                                          
instagram_username                        : essa.teryuavainen
twitter_username                          : 
github_username                           : alextar04
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Multilingualism
    description                           : English, Russian.
    fontawesome_icon_name                 : star
    
  - title                                 : Plant's category
    description                           : Selection of a 3D model of a plant by category.
    fontawesome_icon_name                 : tree

  - title                                 : Surface
    description                           : Projection of the auxiliary surface for the installation of the model.
    fontawesome_icon_name                 : magic

  - title                                 : Automatic Icon and Metadata
    description                           : Interaction with the plant after installation.
    fontawesome_icon_name                 : right-left

  - title                                 : Easy to Tweak
    description                           : Import custom models in the application [USDZ, OBJ, SCN].
    fontawesome_icon_name                 : unity
  
  - title                                 : Feature List
    description                           : Recording photo collages & AR session.
    fontawesome_icon_name                 : video

# https://fontawesome.com/

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
